import { readFileSync } from "fs";
import path from "path";
import { PrismaClient } from "@prisma/client";
import { hash } from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  const email = (process.env.ADMIN_EMAIL || "admin@example.com").toLowerCase();
  const password = process.env.ADMIN_TEMP_PASSWORD || "";
  const existing = await prisma.user.findUnique({ where: { email } });
  if (!existing) {
    if (password.length < 12) {
      throw new Error("Set ADMIN_TEMP_PASSWORD to at least 12 characters before the first seed.");
    }
    await prisma.user.create({
      data: {
        email,
        name: "Temporary admin",
        passwordHash: await hash(password, 12),
        mustChangePassword: true,
        role: "admin",
      },
    });
    console.log(`Created temporary admin ${email}. Password change is required on first login.`);
  } else {
    console.log(`Admin ${email} already exists. Password was not changed.`);
  }

  await prisma.siteChrome.upsert({
    where: { id: "singleton" },
    update: {},
    create: {
      id: "singleton",
      headerJson: JSON.stringify({
        logoText: "Daulat Drive",
        tagline: "CMS",
        announcement: "Sample content. Replace it from the admin.",
        links: [
          { label: "Home", href: "/" },
          { label: "Journal", href: "/blog" },
          { label: "Products", href: "/products" },
          { label: "Portfolio", href: "/portfolio" },
        ],
      }),
      footerJson: JSON.stringify({
        blurb: "Head office in Daulatpur, Khulna. Edited from the CMS.",
        phone: "+8801330132141",
        email: "mail@gmail.com",
        address: "Daulatpur, Khulna 9202, Bangladesh",
        links: [
          { label: "Admin", href: "/admin" },
          { label: "Sitemap", href: "/sitemap.xml" },
        ],
      }),
    },
  });

  const settings: Record<string, string> = {
    site_name: "Daulat Drive",
    site_url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
    ga_enabled: "false",
    ga_measurement_id: "",
    gsc_method: "meta",
    gsc_verification_token: "",
    revalidate_seconds: "60",
    robots_extra: "",
    smtp_port: "587",
    smtp_secure: "false",
    smtp_from: "Daulat Drive <mail@gmail.com>",
  };
  for (const [key, value] of Object.entries(settings)) {
    await prisma.setting.upsert({ where: { key }, update: {}, create: { key, value } });
  }

  await prisma.page.upsert({
    where: { slug: "home" },
    update: {},
    create: {
      title: "Reliable car rental and sales",
      slug: "home",
      status: "published",
      excerpt: "Daily hires and cars for sale from Daulatpur, Khulna.",
      body: "This homepage is stored in the CMS. Edit it under **Pages**, slug `home`.\n\nCall +8801330132141 or email mail@gmail.com.",
      seoTitle: "Daulat Drive — car rental and sales in Khulna",
      seoDescription: "Hire or buy a car from the Daulatpur desk. Rates in BDT.",
      publishedAt: new Date(),
      sections: {
        create: [
          { key: "hours", label: "Hours", body: "Open daily, 8:00–21:00, at Daulatpur, Khulna 9202.", sortOrder: 0 },
        ],
      },
    },
  });

  await prisma.post.upsert({
    where: { slug: "how-a-hire-works" },
    update: {},
    create: {
      title: "How a hire works",
      slug: "how-a-hire-works",
      status: "published",
      excerpt: "A request is not a booking until the desk calls you back.",
      body: "Bring a licence and NID. Fuel is full-to-full. A driver is 1,500 BDT per day.",
      authorName: "Daulat Drive desk",
      seoTitle: "How car hire works in Khulna",
      seoDescription: "Papers, fuel, and confirmation for a Daulat Drive hire.",
      publishedAt: new Date(),
    },
  });

  await prisma.product.upsert({
    where: { slug: "toyota-premio-2019" },
    update: {},
    create: {
      name: "Toyota Premio 2019",
      slug: "toyota-premio-2019",
      status: "published",
      description: "Pearl white sedan. Sample product so the admin product editor can be tested. Asking price is stored in paisa-style cents.",
      priceCents: 125000000,
      currency: "BDT",
      sku: "PREMIO-2019",
      seoTitle: "Toyota Premio 2019 for sale",
      seoDescription: "Sample product page generated by the CMS seed.",
    },
  });

  await prisma.portfolioItem.upsert({
    where: { slug: "daulatpur-yard" },
    update: {},
    create: {
      title: "Daulatpur yard",
      slug: "daulatpur-yard",
      status: "published",
      summary: "A short portfolio item for the desk yard.",
      body: "Replace this image and copy from the portfolio editor.",
      client: "Daulat Drive",
      year: "2026",
      tags: "yard, khulna",
      seoTitle: "Daulatpur yard",
      seoDescription: "Sample portfolio item.",
    },
  });

  const carsPath = path.join(__dirname, "../public/data/cars.json");
  try {
    const cars = JSON.parse(readFileSync(carsPath, "utf8")) as Array<Record<string, unknown>>;
    for (const car of cars) {
      const slug = String(car.slug || car.id);
      const images = Array.isArray(car.local_images) ? car.local_images.map(String) : [];
      const data = {
        make: String(car.make || ""),
        model: String(car.model || ""),
        year: Number(car.year || 0),
        type: String(car.type || "Sedan"),
        segment: String(car.segment || ""),
        seats: Number(car.seats || 5),
        transmission: String(car.transmission || ""),
        fuel: String(car.fuel || ""),
        engine: String(car.engine || ""),
        color: String(car.color || ""),
        luggage: String(car.luggage || ""),
        rentalRate: Number(car.rental_rate_per_day || 0),
        salePrice: Number(car.sale_price || 0),
        mileageKm: Number(car.mileage_km || 0),
        availability: String(car.availability_status || "available"),
        focus: String(car.focus || "rental"),
        features: JSON.stringify(car.features || []),
        description: String(car.description || ""),
        image: images[0] || "",
        images: JSON.stringify(images),
        published: true,
      };
      await prisma.car.upsert({ where: { slug }, update: {}, create: { slug, ...data } });
    }
    console.log(`Fleet seed checked ${cars.length} cars. Existing cars were left unchanged.`);
  } catch (error) {
    console.log("Car seed skipped.", error instanceof Error ? error.message : error);
  }

  console.log("Seed finished.");
}

main().finally(() => prisma.$disconnect());
